import React, { useState, useEffect } from 'react';
import { storageService } from '../services/storageService';
import { Button } from '../components/Button';
import { Input } from '../components/Input';
import { TimeLog, User, QRCodeData } from '../types';
import { useNavigate } from 'react-router-dom';
import { LogOut, History, Clock, QrCode, Type, CheckCircle, AlertCircle, RefreshCw } from 'lucide-react';
import { QrReader } from 'react-qr-reader'; // Note: In a real project, consider using a different library if strict mode issues arise.

export const EmployeeDashboard: React.FC = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState<User | null>(null);
  const [activeTab, setActiveTab] = useState<'register' | 'history'>('register');
  const [logs, setLogs] = useState<TimeLog[]>([]);
  
  // Register State
  const [mode, setMode] = useState<'scan' | 'manual' | null>(null);
  const [manualCode, setManualCode] = useState('');
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [statusMsg, setStatusMsg] = useState('');

  useEffect(() => {
    const session = storageService.getSession();
    if (!session) {
      navigate('/');
      return;
    }
    setUser(session);
    refreshLogs(session.id);
  }, [navigate]);

  const refreshLogs = (userId: string) => {
    const allLogs = storageService.getLogs();
    const userLogs = allLogs.filter(l => l.userId === userId);
    setLogs(userLogs);
  };

  const handleLogout = () => {
    storageService.logout();
    navigate('/');
  };

  const registerPoint = async (method: 'QR' | 'MANUAL') => {
    if (!user) return;
    
    // In a real scenario with Manual Code, we'd need to validate against the Tablet's current code.
    // However, without a backend, we can't easily validate manual codes entered on the phone against the tablet's state
    // unless the employee enters the code generated by the tablet.
    // For this demo, we assume any 4-digit code is "valid" but in a real app, 
    // we would send this code to the Google Sheet script to validate server-side.
    
    const now = new Date();
    
    // Determine Type (Entrada/Saida) based on last log
    // Simple logic: If last log today was Entrada, this is Saida.
    const todayLogs = logs.filter(l => {
      const d = new Date(l.timestamp);
      return d.getDate() === now.getDate() && 
             d.getMonth() === now.getMonth() && 
             d.getFullYear() === now.getFullYear();
    });
    
    let type: 'ENTRADA' | 'SAIDA' = 'ENTRADA';
    if (todayLogs.length > 0 && todayLogs[0].type === 'ENTRADA') {
        type = 'SAIDA';
    }

    const newLog: TimeLog = {
      id: crypto.randomUUID(),
      userId: user.id,
      userName: user.name,
      timestamp: now.toISOString(),
      type: type,
      method: method,
      synced: false
    };

    try {
      await storageService.addLog(newLog);
      setStatus('success');
      setStatusMsg(`Ponto de ${type} registrado com sucesso!`);
      setManualCode('');
      setMode(null);
      refreshLogs(user.id);
      
      // Reset status after 3 seconds
      setTimeout(() => setStatus('idle'), 3000);
    } catch (e) {
      setStatus('error');
      setStatusMsg('Erro ao salvar ponto.');
    }
  };

  const handleScan = (result: any, error: any) => {
    if (result) {
        try {
            const data: QRCodeData = JSON.parse(result?.text);
            // Validate time
            const now = Date.now();
            if (now > data.validUntil) {
                setStatus('error');
                setStatusMsg('QR Code expirado.');
                setMode(null);
                return;
            }
            // If valid
            registerPoint('QR');
        } catch (e) {
            setStatus('error');
            setStatusMsg('QR Code inválido.');
        }
    }
  };

  const handleManualSubmit = (e: React.FormEvent) => {
      e.preventDefault();
      if (manualCode.length !== 4) {
          setStatus('error');
          setStatusMsg('Código deve ter 4 dígitos.');
          return;
      }
      registerPoint('MANUAL');
  };

  const calculateMonthlyHours = () => {
     // Simplistic calculation for demo
     return "160h 00m";
  };

  return (
    <div className="min-h-screen bg-gray-50 pb-20 md:pb-0">
      {/* Header */}
      <header className="bg-white shadow-sm sticky top-0 z-20">
        <div className="max-w-3xl mx-auto px-4 py-4 flex justify-between items-center">
          <div>
             <h1 className="text-xl font-bold text-gray-800">Olá, {user?.name.split(' ')[0]}</h1>
             <p className="text-xs text-gray-500">{user?.position || 'Colaborador'}</p>
          </div>
          <button onClick={handleLogout} className="text-gray-400 hover:text-red-500">
            <LogOut size={24} />
          </button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto p-4 space-y-6">
        
        {/* Status Notification */}
        {status !== 'idle' && (
            <div className={`p-4 rounded-xl flex items-center gap-3 shadow-sm ${status === 'success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>
                {status === 'success' ? <CheckCircle /> : <AlertCircle />}
                <span className="font-medium">{statusMsg}</span>
            </div>
        )}

        {/* Tab Navigation */}
        <div className="flex bg-white p-1 rounded-xl shadow-sm border border-gray-100">
            <button 
                onClick={() => setActiveTab('register')}
                className={`flex-1 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'register' ? 'bg-blue-600 text-white shadow-md' : 'text-gray-500 hover:bg-gray-50'}`}
            >
                Registrar Ponto
            </button>
            <button 
                onClick={() => setActiveTab('history')}
                className={`flex-1 py-2 rounded-lg text-sm font-medium transition-all ${activeTab === 'history' ? 'bg-blue-600 text-white shadow-md' : 'text-gray-500 hover:bg-gray-50'}`}
            >
                Histórico
            </button>
        </div>

        {activeTab === 'register' ? (
            <div className="space-y-6">
                {/* Clock Card */}
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 text-center">
                    <p className="text-gray-400 text-sm uppercase tracking-wide font-semibold mb-2">Hora Atual</p>
                    <div className="text-4xl font-mono font-bold text-gray-800">
                        {new Date().toLocaleTimeString('pt-BR', {hour: '2-digit', minute:'2-digit'})}
                    </div>
                    <div className="text-gray-500 text-sm mt-1">
                        {new Date().toLocaleDateString('pt-BR', {weekday: 'long', day:'numeric', month:'long'})}
                    </div>
                </div>

                {/* Actions */}
                {!mode ? (
                    <div className="grid grid-cols-2 gap-4">
                        <button 
                            onClick={() => setMode('scan')}
                            className="bg-blue-600 hover:bg-blue-700 text-white p-6 rounded-2xl shadow-md transition-all flex flex-col items-center justify-center gap-3 aspect-square"
                        >
                            <QrCode size={40} />
                            <span className="font-medium">Escanear QR</span>
                        </button>
                        <button 
                            onClick={() => setMode('manual')}
                            className="bg-white hover:bg-gray-50 text-blue-600 border-2 border-blue-100 p-6 rounded-2xl shadow-sm transition-all flex flex-col items-center justify-center gap-3 aspect-square"
                        >
                            <Type size={40} />
                            <span className="font-medium">Digitar Código</span>
                        </button>
                    </div>
                ) : (
                    <div className="bg-white p-6 rounded-2xl shadow-lg border border-gray-100 relative">
                        <button 
                            onClick={() => setMode(null)} 
                            className="absolute top-4 right-4 text-gray-400 hover:text-gray-600"
                        >
                            <LogOut className="rotate-180" size={20} />
                        </button>

                        <h3 className="text-lg font-bold mb-4 text-center">
                            {mode === 'scan' ? 'Aponte para o Tablet' : 'Código do Tablet'}
                        </h3>

                        {mode === 'scan' && (
                            <div className="overflow-hidden rounded-lg bg-black aspect-square relative">
                                <QrReader
                                    onResult={handleScan}
                                    constraints={{ facingMode: 'environment' }}
                                    className="w-full h-full"
                                />
                                <div className="absolute inset-0 border-2 border-white/30 pointer-events-none flex items-center justify-center">
                                    <div className="w-48 h-48 border-2 border-blue-500 rounded-lg pulse-ring"></div>
                                </div>
                            </div>
                        )}

                        {mode === 'manual' && (
                            <form onSubmit={handleManualSubmit} className="space-y-4">
                                <Input 
                                    placeholder="0000"
                                    value={manualCode}
                                    onChange={(e) => setManualCode(e.target.value.replace(/\D/g, '').slice(0, 4))}
                                    className="text-center text-3xl tracking-[1em] font-mono h-20"
                                    type="tel"
                                    autoFocus
                                />
                                <Button type="submit" fullWidth disabled={manualCode.length !== 4}>
                                    Confirmar
                                </Button>
                            </form>
                        )}
                    </div>
                )}
            </div>
        ) : (
            <div className="space-y-4">
                 {/* Summary Card */}
                 <div className="bg-gradient-to-r from-blue-600 to-blue-800 p-6 rounded-2xl shadow-md text-white">
                    <div className="flex items-center gap-3 mb-2 opacity-80">
                        <Clock size={18} />
                        <span className="text-sm font-medium">Horas no Mês (Estimado)</span>
                    </div>
                    <div className="text-3xl font-bold">
                        {calculateMonthlyHours()}
                    </div>
                 </div>

                 <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
                    <div className="p-4 border-b border-gray-100 bg-gray-50">
                        <h3 className="font-semibold text-gray-700 flex items-center gap-2">
                            <History size={18} /> Últimos Registros
                        </h3>
                    </div>
                    {logs.length === 0 ? (
                        <div className="p-8 text-center text-gray-400">Nenhum registro encontrado.</div>
                    ) : (
                        <div className="divide-y divide-gray-100">
                            {logs.map(log => (
                                <div key={log.id} className="p-4 flex justify-between items-center">
                                    <div className="flex items-center gap-3">
                                        <div className={`w-2 h-10 rounded-full ${log.type === 'ENTRADA' ? 'bg-green-500' : 'bg-orange-500'}`}></div>
                                        <div>
                                            <p className="font-bold text-gray-800">{log.type}</p>
                                            <p className="text-xs text-gray-500">
                                                {new Date(log.timestamp).toLocaleDateString()}
                                            </p>
                                        </div>
                                    </div>
                                    <div className="text-right">
                                        <p className="text-lg font-mono font-medium text-gray-700">
                                            {new Date(log.timestamp).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                                        </p>
                                        <div className="flex items-center justify-end gap-1 mt-1">
                                            {log.synced ? (
                                                <span className="text-[10px] bg-green-100 text-green-700 px-1.5 py-0.5 rounded flex items-center gap-1">
                                                    <CheckCircle size={8} /> Sync
                                                </span>
                                            ) : (
                                                <span className="text-[10px] bg-gray-100 text-gray-500 px-1.5 py-0.5 rounded flex items-center gap-1">
                                                    <RefreshCw size={8} /> Local
                                                </span>
                                            )}
                                            <span className="text-[10px] text-gray-400 bg-gray-50 px-1.5 py-0.5 rounded">{log.method}</span>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    )}
                 </div>
            </div>
        )}
      </main>
    </div>
  );
};